export const RECEIVE_TODAY_DATA = 'RECEIVE_TODAY_DATA';
export const UPDATE_TODAY_DATA = 'UPDATE_TODAY_DATA';
export const RECEIVE_WEEK_DATA = 'RECEIVE_WEEK_DATA';
export const UPDATE_WEEK_OFFSET = 'UPDATE_WEEK_OFFSET';
export const UPDATE_WEEK_OFFSET_MAX = 'UPDATE_WEEK_OFFSET_MAX';
export const RECEIVE_MONTH_DATA = 'RECEIVE_MONTH_DATA';
export const UPDATE_MONTH_OFFSET = 'UPDATE_MONTH_OFFSET';
export const UPDATE_MONTH_OFFSET_MAX = 'UPDATE_MONTH_OFFSET_MAX';
